### ISSUE TITLE
TODO list before demo

### ISSUE THREAD

**Issue by VictorCoder123** [VictorCoder123/webgme-premonition#1]
## TODO list for Improvements before demo

- [x] Adjust size of result image in message window
- [x] Set range for parameters
- [x] Create two models with different result graph by modifying sensitive parameter
- [x] Add documentation for pipeline using DocumentationDecorator 
- [x] Add Icons for all models
